app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['domains' => ['api.ojczystaczysta.dev', 'api.ojczystaczysta.pl'], 'middleware' => 'cors', 'prefix' => 'v1'], function() {
    Route::get('/schedule', 'ScheduleController@all');
    Route::get('/menu', 'MenuController@all');
    Route::get('/slider', 'SliderController@all');
    Route::post('/contact', 'ContactController@send');
});

Route::group(['domains' => ['cms.ojczystaczysta.dev', 'cms.ojczystaczysta.pl']], function() {
    Route::get('auth/login', 'Auth\AuthController@getLogin');
    Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('auth/logout', 'Auth\AuthController@getLogout');

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);

        Route::post('/menu/position', ['as' => 'menu.position', 'uses' => 'MenuController@position']);
        Route::post('/menu/items/position', ['as' => 'menu.items.position', 'uses' => 'MenuItemController@position']);
        Route::post('/slider/position', ['as' => 'slider.position', 'uses' => 'SliderController@position']);
        Route::resource('slider', 'SliderController', ['except' => 'show']);
        Route::resource('schedule', 'ScheduleController', ['except' => 'show']);
        Route::resource('menu', 'MenuController', ['except' => ['create', 'show']]);
        Route::resource('menu.items', 'MenuItemController', ['except' => 'show']);

    });
});

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'position', 'price'];

    /**
     * Get the comments for the blog post.
     */
    public function items()
    {
        return $this->hasMany('App\MenuItem');
    }

    public function scopeOrdered($query, $id = null) {
        $query = $query->orderBy('position', 'asc')->with(['items' => function($q) {
            $q->orderBy('position', 'asc');
        }]);

        if($id) {
            return $query->where('id', $id)->first();
        }

        return $query->get();
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Menu;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use League\Flysystem\NotSupportedException;

class MenuController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entities = Menu::ordered();
        return view('menu.index', compact('entities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        throw new NotSupportedException();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        Menu::create($data);

        return back()->with(['status' => 'success', 'message' => 'Menu zostało utworzone']);
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function all()
    {
        return response()->json(Menu::ordered());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entities = Menu::ordered();
        $entity = Menu::ordered($id);
//        $entity = Menu::where('id', $id)->with(['items' => function($query) {
//            $query->orderBy('position', 'asc');
//        }])->first();

        return view('menu.edit', compact('entities', 'entity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $entity = Menu::find($id);

        $data = $request->all();
        $entity->update($data);

        return back()->with(['status' => 'success', 'message' => 'Menu zostało zaktualizowane']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Menu::destroy($id);

        return redirect()->route('menu.index')->with(['status' => 'success', 'message' => 'Menu zostało usunięte']);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function position(Request $request) {
        $items = $request->get('items');

        foreach($items as $item) {
            Menu::find($item['id'])->update(['position' => $item['position']]);
        }

        return response()->json([
            'status' => 'success',
            'message' => 'Pozycje zostały zapisane'
        ]);
    }
}

resources/views/menu/edit.blade.php
@extends('menu.layout')

@section('form')
    {!! Form::model($entity, ['route' => ['menu.update', $entity->id], 'method' => 'PUT'])  !!}
    @include('menu.form')
    {!! Form::close() !!}
@endsection

@section('list')
    <div class="panel panel-default panel-sortable" data-url="{{ route('menu.items.position') }}">
        <div class="panel-heading">
            <h3 class="panel-title">Elementy menu</h3>

            <div class="panel-action">
                <button class="btn btn-default btn-cancel"><span class="glyphicon glyphicon-remove"></span></button>
                <button class="btn btn-default btn-ok" data-url="{{ route('slider.position') }}"><span class="glyphicon glyphicon-ok"></span></button>
                <button class="btn btn-default btn-sort"><span class="glyphicon glyphicon-sort"></span></button>
                <a href="{{ route('menu.items.create', [$entity->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span></a>
            </div>
        </div>

        <div class="list-group">
            @forelse($entity->items as $idx => $item)
                <a href="{{ route('menu.items.edit', [$entity->id, $item->id]) }}" data-id="{{ $item->id }}" class="list-group-item {{ Request::url() == (route('menu.items.edit', $item->id)) ? 'active' : null }}">
                    <span class="list-group-element">
                        <span class="number">{{$idx + 1}}.</span> {{ $item->name }}

                        <span class="item-action">
                            <span class="btn btn-sm btn-default btn-remove"><span class="glyphicon glyphicon-trash"></span></span>
                        </span>
                    </span>

                    <span class="list-group-remove">
                        Czy na pewno chcesz usunąć element?

                        <span class="item-action">
                            <span class="btn btn-sm btn-default btn-remove-no"><span class="glyphicon glyphicon-remove"></span></span>
                            {!! Form::open(['method' => 'DELETE', 'route' => ['menu.items.destroy', $entity->id, $item->id]]) !!}
                                <button class="btn btn-sm btn-danger btn-remove-ok"><span class="glyphicon glyphicon-ok"></span></button>
                            {!! Form::close() !!}
                        </span>
                    </span>
                </a>
            @empty
                <p class="list-group-item">Lista jest pusta.</p>
            @endforelse
        </div>
    </div>
@endsection

resources/views/menu/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <p><strong>Wystąpiły błedy:</strong></p>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group">
    {!! Form::label('name', 'Nazwa') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('price', 'Cena') !!}
    <p class="form-helper">Wpisz cenę bez waluty. Cena będzie pokazana w PLN.</p>

    <div class="input-group">
        {!! Form::text('price', null, ['class' => 'form-control']) !!}
        <div class="input-group-addon">zł</div>
    </div>
</div>

<div class="form-group">
    <a class="btn btn-default" href="{{ route('schedule.index') }}">Anuluj</a>
    {!! Form::submit('Zapisz', ['class' => 'btn btn-primary']) !!}
</div>

@section('script')
    <script>
        $(document).ready(function() {
            $('input[name="price"]').on('input', function(e) {
                this.value = this.value.replace(/[^0-9,]/g, '');
            });
        });
    </script>
@endsection

resources/views/menu/index.blade.php
@extends('menu.layout')

@section('form')
    <p>Kliknij na element z listy po prawej aby nim zrządzać.</p>
@endsection

resources/views/menu/layout.blade.php
@extends('layout')

@section('body')

    <ul class="toaster">
        @if(Session::has('status'))
            <li class="alert alert-{{ Session::get('status') }} alert-dismissible" role="alert">
                {{ Session::get('message') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </li>
        @endif
    </ul>

    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default" id="panel-form">
                <div class="panel-heading">
                    <h3 class="panel-title">Formularz</h3>
                </div>
                <div class="panel-body">
                    @yield('form')

                    <div class="form-disabled"></div>
                </div>
            </div>

            @yield('list')
        </div>

        <div class="col-md-4">
            <div class="panel panel-default panel-sortable" data-url="{{ route('menu.position') }}">
                <div class="panel-heading">
                    <h3 class="panel-title">Rodzaje menu</h3>

                    <div class="panel-action">
                        <button class="btn btn-default btn-cancel"><span class="glyphicon glyphicon-remove"></span></button>
                        <button class="btn btn-default btn-ok" data-url="{{ route('slider.position') }}"><span class="glyphicon glyphicon-ok"></span></button>
                        <button class="btn btn-default btn-sort"><span class="glyphicon glyphicon-sort"></span></button>
                    </div>
                </div>

                <div class="list-group">
                    @forelse($entities as $idx => $entity)
                        <a href="{{ route('menu.edit', $entity->id) }}" data-id="{{ $entity->id }}" class="list-group-item {{ Request::url() == (route('menu.edit', $entity->id)) ? 'active' : null }}">
                            <span class="list-group-element">
                                <span class="number">{{$idx + 1}}.</span> {{ $entity->name }}
                            </span>
                        </a>
                    @empty
                        <p class="list-group-item">Lista jest pusta.</p>
                    @endforelse
                </div>
            </div>
        </div>
    </div>
@endsection